CREATE TABLE "cards_transformed" (
"name" TEXT,
  "value" INTEGER,
  "run_id" TEXT
);
CREATE TABLE "run_modifiers_model_ids" (
"name" TEXT,
  "value" TEXT,
  "run_id" TEXT
);
CREATE TABLE "card_removed_props" (
"name" TEXT,
  "value" INTEGER,
  "run_id" TEXT
);
CREATE TABLE "props.strings" (
"name" TEXT,
  "value" TEXT,
  "run_id" TEXT,
  "player_id" INTEGER
);
CREATE TABLE "run_modifiers" (
"id" TEXT,
  "run_id" TEXT
);
CREATE TABLE "card_props" (
"name" TEXT,
  "value" INTEGER,
  "run_id" TEXT
);
CREATE TABLE "badges" (
"id" TEXT,
  "rarity" TEXT,
  "player_id" INTEGER,
  "run_id" TEXT
);
CREATE TABLE "props.cards" (
"name" TEXT,
  "value.id" TEXT,
  "value.floor_added_to_deck" TEXT,
  "run_id" TEXT,
  "player_id" INTEGER,
  "value.current_upgrade_level" TEXT
);
CREATE TABLE "props.ints" (
"name" TEXT,
  "value" INTEGER,
  "run_id" TEXT,
  "player_id" INTEGER
);
CREATE TABLE "props.bools" (
"name" TEXT,
  "value" INTEGER,
  "run_id" TEXT,
  "player_id" INTEGER
);
CREATE TABLE "potions" (
"id" TEXT,
  "slot_index" REAL,
  "player_id" INTEGER,
  "run_id" TEXT
);

CREATE TABLE "runs" (
"ascension" INTEGER,
  "build_id" TEXT,
  "game_mode" TEXT,
  "killed_by_encounter" TEXT,
  "killed_by_event" TEXT,
  "platform_type" TEXT,
  "run_time" INTEGER,
  "schema_version" INTEGER,
  "seed" TEXT,
  "start_time" INTEGER,
  "was_abandoned" INTEGER,
  "win" INTEGER
);

CREATE UNIQUE INDEX IF NOT EXISTS run_idx ON "runs"("start_time");

CREATE TABLE "map_point" (
"map_point_type" TEXT,
  "run_id" TEXT,
  "act" TEXT,
  "floors" TEXT
);
CREATE TABLE "rooms" (
"model_id" TEXT,
  "room_type" TEXT,
  "turns_taken" INTEGER,
  "monster_ids" TEXT,
  "run_id" TEXT
);
CREATE TABLE "player_stats" (
"current_gold" INTEGER,
  "current_hp" INTEGER,
  "damage_taken" INTEGER,
  "gold_gained" INTEGER,
  "gold_lost" INTEGER,
  "gold_spent" INTEGER,
  "gold_stolen" INTEGER,
  "hp_healed" INTEGER,
  "max_hp" INTEGER,
  "max_hp_gained" INTEGER,
  "max_hp_lost" INTEGER,
  "player_id" INTEGER,
  "cards_gained" TEXT,
  "run_id" TEXT,
  "rest_site_choices" TEXT,
  "potion_used" TEXT,
  "upgraded_cards" TEXT,
  "relics_removed" TEXT,
  "bought_colorless" TEXT,
  "bought_potions" TEXT,
  "bought_relics" TEXT,
  "potion_discarded" TEXT,
  "downgraded_cards" TEXT,
  "completed_quests" TEXT
);
CREATE TABLE "ancient_choice" (
"TextKey" TEXT,
  "was_chosen" INTEGER,
  "title.key" TEXT,
  "title.table" TEXT,
  "run_id" TEXT
);
CREATE TABLE "event_choices" (
"title.key" TEXT,
  "title.table" TEXT,
  "run_id" TEXT,
  "variables.SmashHPGain.type" TEXT,
  "variables.SmashHPGain.decimal_value" TEXT,
  "variables.SmashHPGain.bool_value" TEXT,
  "variables.SmashHPGain.string_value" TEXT,
  "variables.DecipherMaxHpLoss.type" TEXT,
  "variables.DecipherMaxHpLoss.decimal_value" TEXT,
  "variables.DecipherMaxHpLoss.bool_value" TEXT,
  "variables.DecipherMaxHpLoss.string_value" TEXT,
  "variables.BargainBinCost.type" TEXT,
  "variables.BargainBinCost.decimal_value" TEXT,
  "variables.BargainBinCost.bool_value" TEXT,
  "variables.BargainBinCost.string_value" TEXT,
  "variables.MysteryBoxCost.type" TEXT,
  "variables.MysteryBoxCost.decimal_value" TEXT,
  "variables.MysteryBoxCost.bool_value" TEXT,
  "variables.MysteryBoxCost.string_value" TEXT,
  "variables.FeaturedItemCost.type" TEXT,
  "variables.FeaturedItemCost.decimal_value" TEXT,
  "variables.FeaturedItemCost.bool_value" TEXT,
  "variables.FeaturedItemCost.string_value" TEXT,
  "variables.MysteryBoxRelicCount.type" TEXT,
  "variables.MysteryBoxRelicCount.decimal_value" TEXT,
  "variables.MysteryBoxRelicCount.bool_value" TEXT,
  "variables.MysteryBoxRelicCount.string_value" TEXT,
  "variables.MysteryBoxCombatCount.type" TEXT,
  "variables.MysteryBoxCombatCount.decimal_value" TEXT,
  "variables.MysteryBoxCombatCount.bool_value" TEXT,
  "variables.MysteryBoxCombatCount.string_value" TEXT,
  "variables.WongoPointAmount.type" TEXT,
  "variables.WongoPointAmount.decimal_value" TEXT,
  "variables.WongoPointAmount.bool_value" TEXT,
  "variables.WongoPointAmount.string_value" TEXT,
  "variables.RemainingWongoPointAmount.type" TEXT,
  "variables.RemainingWongoPointAmount.decimal_value" TEXT,
  "variables.RemainingWongoPointAmount.bool_value" TEXT,
  "variables.RemainingWongoPointAmount.string_value" TEXT,
  "variables.TotalWongoBadgeAmount.type" TEXT,
  "variables.TotalWongoBadgeAmount.decimal_value" TEXT,
  "variables.TotalWongoBadgeAmount.bool_value" TEXT,
  "variables.TotalWongoBadgeAmount.string_value" TEXT,
  "variables.RandomRelic.type" TEXT,
  "variables.RandomRelic.decimal_value" TEXT,
  "variables.RandomRelic.bool_value" TEXT,
  "variables.RandomRelic.string_value" TEXT,
  "variables.ResistCurse.type" TEXT,
  "variables.ResistCurse.decimal_value" TEXT,
  "variables.ResistCurse.bool_value" TEXT,
  "variables.ResistCurse.string_value" TEXT,
  "variables.Enchantment.type" TEXT,
  "variables.Enchantment.decimal_value" TEXT,
  "variables.Enchantment.bool_value" TEXT,
  "variables.Enchantment.string_value" TEXT,
  "variables.Card.type" TEXT,
  "variables.Card.decimal_value" TEXT,
  "variables.Card.bool_value" TEXT,
  "variables.Card.string_value" TEXT,
  "variables.Relic.type" TEXT,
  "variables.Relic.decimal_value" TEXT,
  "variables.Relic.bool_value" TEXT,
  "variables.Relic.string_value" TEXT,
  "variables.Curse.type" TEXT,
  "variables.Curse.decimal_value" TEXT,
  "variables.Curse.bool_value" TEXT,
  "variables.Curse.string_value" TEXT,
  "variables.BirdCard.type" TEXT,
  "variables.BirdCard.decimal_value" TEXT,
  "variables.BirdCard.bool_value" TEXT,
  "variables.BirdCard.string_value" TEXT,
  "variables.SnakeEnchantment.type" TEXT,
  "variables.SnakeEnchantment.decimal_value" TEXT,
  "variables.SnakeEnchantment.bool_value" TEXT,
  "variables.SnakeEnchantment.string_value" TEXT,
  "variables.ToricCard.type" TEXT,
  "variables.ToricCard.decimal_value" TEXT,
  "variables.ToricCard.bool_value" TEXT,
  "variables.ToricCard.string_value" TEXT,
  "variables.SmallChestGold.type" TEXT,
  "variables.SmallChestGold.decimal_value" TEXT,
  "variables.SmallChestGold.bool_value" TEXT,
  "variables.SmallChestGold.string_value" TEXT,
  "variables.LargeChestGold.type" TEXT,
  "variables.LargeChestGold.decimal_value" TEXT,
  "variables.LargeChestGold.bool_value" TEXT,
  "variables.LargeChestGold.string_value" TEXT,
  "variables.Enchantment1.type" TEXT,
  "variables.Enchantment1.decimal_value" TEXT,
  "variables.Enchantment1.bool_value" TEXT,
  "variables.Enchantment1.string_value" TEXT,
  "variables.Enchantment2.type" TEXT,
  "variables.Enchantment2.decimal_value" TEXT,
  "variables.Enchantment2.bool_value" TEXT,
  "variables.Enchantment2.string_value" TEXT,
  "variables.Enchantment3.type" TEXT,
  "variables.Enchantment3.decimal_value" TEXT,
  "variables.Enchantment3.bool_value" TEXT,
  "variables.Enchantment3.string_value" TEXT,
  "variables.FoulPotions.type" TEXT,
  "variables.FoulPotions.decimal_value" TEXT,
  "variables.FoulPotions.bool_value" TEXT,
  "variables.FoulPotions.string_value" TEXT,
  "variables.Potion.type" TEXT,
  "variables.Potion.decimal_value" TEXT,
  "variables.Potion.bool_value" TEXT,
  "variables.Potion.string_value" TEXT,
  "variables.BatheCurses.type" TEXT,
  "variables.BatheCurses.decimal_value" TEXT,
  "variables.BatheCurses.bool_value" TEXT,
  "variables.BatheCurses.string_value" TEXT,
  "variables.RandomCard.type" TEXT,
  "variables.RandomCard.decimal_value" TEXT,
  "variables.RandomCard.bool_value" TEXT,
  "variables.RandomCard.string_value" TEXT,
  "variables.HpLoss.type" TEXT,
  "variables.HpLoss.decimal_value" TEXT,
  "variables.HpLoss.bool_value" TEXT,
  "variables.HpLoss.string_value" TEXT,
  "variables.TopRelicOwned.type" TEXT,
  "variables.TopRelicOwned.decimal_value" TEXT,
  "variables.TopRelicOwned.bool_value" TEXT,
  "variables.TopRelicOwned.string_value" TEXT,
  "variables.TopRelicNew.type" TEXT,
  "variables.TopRelicNew.decimal_value" TEXT,
  "variables.TopRelicNew.bool_value" TEXT,
  "variables.TopRelicNew.string_value" TEXT,
  "variables.MiddleRelicOwned.type" TEXT,
  "variables.MiddleRelicOwned.decimal_value" TEXT,
  "variables.MiddleRelicOwned.bool_value" TEXT,
  "variables.MiddleRelicOwned.string_value" TEXT,
  "variables.MiddleRelicNew.type" TEXT,
  "variables.MiddleRelicNew.decimal_value" TEXT,
  "variables.MiddleRelicNew.bool_value" TEXT,
  "variables.MiddleRelicNew.string_value" TEXT,
  "variables.BottomRelicOwned.type" TEXT,
  "variables.BottomRelicOwned.decimal_value" TEXT,
  "variables.BottomRelicOwned.bool_value" TEXT,
  "variables.BottomRelicOwned.string_value" TEXT,
  "variables.BottomRelicNew.type" TEXT,
  "variables.BottomRelicNew.decimal_value" TEXT,
  "variables.BottomRelicNew.bool_value" TEXT,
  "variables.BottomRelicNew.string_value" TEXT,
  "variables.BoneTeaCost.type" TEXT,
  "variables.BoneTeaCost.decimal_value" TEXT,
  "variables.BoneTeaCost.bool_value" TEXT,
  "variables.BoneTeaCost.string_value" TEXT,
  "variables.EmberTeaCost.type" TEXT,
  "variables.EmberTeaCost.decimal_value" TEXT,
  "variables.EmberTeaCost.bool_value" TEXT,
  "variables.EmberTeaCost.string_value" TEXT,
  "variables.BoneTeaDescription.type" TEXT,
  "variables.BoneTeaDescription.decimal_value" TEXT,
  "variables.BoneTeaDescription.bool_value" TEXT,
  "variables.BoneTeaDescription.string_value" TEXT,
  "variables.EmberTeaDescription.type" TEXT,
  "variables.EmberTeaDescription.decimal_value" TEXT,
  "variables.EmberTeaDescription.bool_value" TEXT,
  "variables.EmberTeaDescription.string_value" TEXT,
  "variables.TeaOfDiscourtesyDescription.type" TEXT,
  "variables.TeaOfDiscourtesyDescription.decimal_value" TEXT,
  "variables.TeaOfDiscourtesyDescription.bool_value" TEXT,
  "variables.TeaOfDiscourtesyDescription.string_value" TEXT,
  "variables.Card1.type" TEXT,
  "variables.Card1.decimal_value" TEXT,
  "variables.Card1.bool_value" TEXT,
  "variables.Card1.string_value" TEXT,
  "variables.Card2.type" TEXT,
  "variables.Card2.decimal_value" TEXT,
  "variables.Card2.bool_value" TEXT,
  "variables.Card2.string_value" TEXT,
  "variables.Setting1Hp.type" TEXT,
  "variables.Setting1Hp.decimal_value" TEXT,
  "variables.Setting1Hp.bool_value" TEXT,
  "variables.Setting1Hp.string_value" TEXT,
  "variables.Setting2Hp.type" TEXT,
  "variables.Setting2Hp.decimal_value" TEXT,
  "variables.Setting2Hp.bool_value" TEXT,
  "variables.Setting2Hp.string_value" TEXT,
  "variables.Setting3Hp.type" TEXT,
  "variables.Setting3Hp.decimal_value" TEXT,
  "variables.Setting3Hp.bool_value" TEXT,
  "variables.Setting3Hp.string_value" TEXT,
  "variables.Rarity.type" TEXT,
  "variables.Rarity.decimal_value" TEXT,
  "variables.Rarity.bool_value" TEXT,
  "variables.Rarity.string_value" TEXT,
  "variables.UncoverFutureCost.type" TEXT,
  "variables.UncoverFutureCost.decimal_value" TEXT,
  "variables.UncoverFutureCost.bool_value" TEXT,
  "variables.UncoverFutureCost.string_value" TEXT,
  "variables.UncoverFutureProphesizeCount.type" TEXT,
  "variables.UncoverFutureProphesizeCount.decimal_value" TEXT,
  "variables.UncoverFutureProphesizeCount.bool_value" TEXT,
  "variables.UncoverFutureProphesizeCount.string_value" TEXT,
  "variables.PaymentPlanCount.type" TEXT,
  "variables.PaymentPlanCount.decimal_value" TEXT,
  "variables.PaymentPlanCount.bool_value" TEXT,
  "variables.PaymentPlanCount.string_value" TEXT,
  "variables.CurseTitle.type" TEXT,
  "variables.CurseTitle.decimal_value" TEXT,
  "variables.CurseTitle.bool_value" TEXT,
  "variables.CurseTitle.string_value" TEXT,
  "variables.SoloGold.type" TEXT,
  "variables.SoloGold.decimal_value" TEXT,
  "variables.SoloGold.bool_value" TEXT,
  "variables.SoloGold.string_value" TEXT,
  "variables.JoinForcesGold.type" TEXT,
  "variables.JoinForcesGold.decimal_value" TEXT,
  "variables.JoinForcesGold.bool_value" TEXT,
  "variables.JoinForcesGold.string_value" TEXT,
  "variables.EntrantNumber.type" TEXT,
  "variables.EntrantNumber.decimal_value" TEXT,
  "variables.EntrantNumber.bool_value" TEXT,
  "variables.EntrantNumber.string_value" TEXT,
  "variables.CurrentDishTitle.type" TEXT,
  "variables.CurrentDishTitle.decimal_value" TEXT,
  "variables.CurrentDishTitle.bool_value" TEXT,
  "variables.CurrentDishTitle.string_value" TEXT,
  "variables.LastDishTitle.type" TEXT,
  "variables.LastDishTitle.decimal_value" TEXT,
  "variables.LastDishTitle.bool_value" TEXT,
  "variables.LastDishTitle.string_value" TEXT,
  "variables.DrinkRandomPotion.type" TEXT,
  "variables.DrinkRandomPotion.decimal_value" TEXT,
  "variables.DrinkRandomPotion.bool_value" TEXT,
  "variables.DrinkRandomPotion.string_value" TEXT,
  "variables.DrinkMaxHpGain.type" TEXT,
  "variables.DrinkMaxHpGain.decimal_value" TEXT,
  "variables.DrinkMaxHpGain.bool_value" TEXT,
  "variables.DrinkMaxHpGain.string_value" TEXT,
  "variables.PushHpLoss.type" TEXT,
  "variables.PushHpLoss.decimal_value" TEXT,
  "variables.PushHpLoss.bool_value" TEXT,
  "variables.PushHpLoss.string_value" TEXT,
  "variables.PushVigorousAmount.type" TEXT,
  "variables.PushVigorousAmount.decimal_value" TEXT,
  "variables.PushVigorousAmount.bool_value" TEXT,
  "variables.PushVigorousAmount.string_value" TEXT,
  "variables.BreathingTechniquesCost.type" TEXT,
  "variables.BreathingTechniquesCost.decimal_value" TEXT,
  "variables.BreathingTechniquesCost.bool_value" TEXT,
  "variables.BreathingTechniquesCost.string_value" TEXT,
  "variables.EmotionalAwarenessCost.type" TEXT,
  "variables.EmotionalAwarenessCost.decimal_value" TEXT,
  "variables.EmotionalAwarenessCost.bool_value" TEXT,
  "variables.EmotionalAwarenessCost.string_value" TEXT,
  "variables.ArachnidAcupunctureCost.type" TEXT,
  "variables.ArachnidAcupunctureCost.decimal_value" TEXT,
  "variables.ArachnidAcupunctureCost.bool_value" TEXT,
  "variables.ArachnidAcupunctureCost.string_value" TEXT,
  "variables.MaxHpLoss.type" TEXT,
  "variables.MaxHpLoss.decimal_value" TEXT,
  "variables.MaxHpLoss.bool_value" TEXT,
  "variables.MaxHpLoss.string_value" TEXT
);
CREATE TABLE "card_choices" (
"was_picked" INTEGER,
  "card.id" TEXT,
  "card.floor_added_to_deck" TEXT,
  "run_id" TEXT,
  "card.current_upgrade_level" TEXT,
  "card.enchantment.amount" TEXT,
  "card.enchantment.id" TEXT
);
CREATE TABLE "relic_choices" (
"choice" TEXT,
  "was_picked" INTEGER,
  "run_id" TEXT
);
CREATE TABLE "potion_choices" (
"choice" TEXT,
  "was_picked" INTEGER,
  "run_id" TEXT
);
CREATE TABLE "cards_removed" (
"floor_added_to_deck" INTEGER,
  "id" TEXT,
  "run_id" TEXT,
  "current_upgrade_level" TEXT,
  "enchantment.amount" TEXT,
  "enchantment.id" TEXT
);
CREATE TABLE "cards_enchanted" (
"enchantment" TEXT,
  "card.enchantment.amount" INTEGER,
  "card.enchantment.id" TEXT,
  "card.floor_added_to_deck" INTEGER,
  "card.id" TEXT,
  "run_id" TEXT,
  "card.current_upgrade_level" TEXT
);
CREATE TABLE "deck" (
"floor_added_to_deck" INTEGER,
  "id" TEXT,
  "player_id" INTEGER,
  "run_id" TEXT,
  "current_upgrade_level" TEXT,
  "enchantment.amount" TEXT,
  "enchantment.id" TEXT
);
CREATE TABLE "player_relics" (
"floor_added_to_deck" INTEGER,
  "id" TEXT,
  "player_id" INTEGER,
  "run_id" TEXT
);
CREATE TABLE "players" (
"character" TEXT,
  "id" INTEGER,
  "max_potion_slot_count" INTEGER,
  "run_id" TEXT
);
CREATE TABLE "props.model_ids" (
"name" TEXT,
  "value" TEXT,
  "run_id" TEXT,
  "player_id" INTEGER
);